### ISSUE TITLE
Offer HTTPS

### ISSUE THREAD

**Issue by qopisbel** [droidbreak/droidbreak.github.io#18]
Cloudflare offers free SSL certificates. [This guide](https://me.net.nz/blog/github-pages-secure-with-cloudflare/) may be useful.

**Comment by repat** [comment]
Pretty cool :) I think GitHub might offer [Let's encrypt](https://letsencrypt.org/) later this year but I'll see if I can use Cloudflare until then.

**Comment by repat** [comment]
Ok, I tried Cloudflare, thanks for the tip. Let's see if it works.

**Comment by qopisbel** [comment]
:+1:

**Comment by repat** [comment]
It worked.
