### ISSUE TITLE
New Categories

### ISSUE THREAD

**Issue by ghost** [droidbreak/droidbreak.github.io#25]
Possible additions:

- [x] **Security**

[FreeOTP](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp)
[KeePassDroid](https://play.google.com/store/apps/details?id=com.android.keepass)
[Wi-Fi Privacy Police](https://play.google.com/store/apps/details?id=be.uhasselt.privacypolice)
[AdAway](https://f-droid.org/repository/browse/?fdid=org.adaway)?

Still in Alpha but worth adding to apps2review
[Android IMSI-Catcher Detector (AIMSICD)](https://f-droid.org/repository/browse/?fdid=com.SecUpwN.AIMSICD)

- [ ] **Games**

[Vector Pinball](https://play.google.com/store/apps/details?id=com.dozingcatsoftware.bouncy)
[Minetest](https://play.google.com/store/apps/details?id=net.minetest.minetest)
[Pixel Dungeon](https://play.google.com/store/apps/details?id=com.watabou.pixeldungeon) 1,000,000+ installs

[2048](https://play.google.com/store/apps/details?id=com.uberspot.a2048) 1,000,000+ installs
[Frozen Bubble](https://play.google.com/store/apps/details?id=org.jfedor.frozenbubble) 1,000,000+ installs
~~[Andor's Trail](https://play.google.com/store/apps/details?id=com.gpl.rpg.AndorsTrail)~~
~~[Recursive Runner](https://play.google.com/store/apps/details?id=net.damsy.soupeaucaillou.recursiveRunner)~~

I'll have to test these out.

Categories can get unwieldy fast and I don't want to add too much clutter to the page. Does anyone have thoughts on how this should be handled? Maybe combine VPN with Security? Get rid of the Video category (only has repeat of VLC entry) and rename Audio/Podcasts to Multimedia?

**Comment by repat** [comment]
Sounds good, I think we can make a Security/VPN category and a multimedia one.

But 6 games are a bit too much i think. What are the best? I would like to keep flappy cow.

**Comment by tedthqme** [comment]
>6 games are a bit too much
Yes, I completely agree. But since games are hard to objectively rate so maybe only choose a few from different categories.
