### ISSUE TITLE
Calendar app

### ISSUE THREAD

**Issue by JeanFred** [droidbreak/droidbreak.github.io#40]
(Subset of #36 in a way).

I will submit a PR with an alternative for Calendar app. Any suggestions?
* Per #36, [Etar](https://f-droid.org/repository/browse/?fdid=ws.xsoh.etar) ?
* [Offline calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=org.sufficientlysecure.localcalendar) ?
* [Standalone Calendar](https://f-droid.org/repository/browse/?fdfilter=calendar&fdid=org.sufficientlysecure.standalonecalendar&fdpage=2)

Thoughts? (I can make all three to get the ball rolling).

**Comment by repat** [comment]
Sounds good to me
