### ISSUE TITLE
Signal is now available at F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [droidbreak/droidbreak.github.io#43]
It ought to be updated.

**Comment by repat** [comment]
Link?

**Comment by pizzamaker** [comment]
The link is broken at the moment: https://f-droid.org/repository/browse/?fdid=org.libresignal

But you can verify this by updating your F-Droid app. It should show up there.

**Comment by repat** [comment]
Not for me, sorry.

Also it's *Libre*Signal. Does that work properly and interact with the normal Signal app?

**Comment by pizzamaker** [comment]
Yes and yes. If we really get technical, F-Droid's Telegram isn't the official Telegram either, it's telegram-foss. Both telegram-foss and libresignal do the same: remove and replace play-services or nonfree analytics.

**Comment by mhyqwvcu** [comment]
Libresignal is only available in the archive repo as it is still in beta. It also lacks VoIP functionality (redphone) so it is not comparable to Signal. Once it's in the main repo it can be reconsidered.

**Comment by repat** [comment]
Still not available, open again if it changes.

**Comment by arthurlutz** [comment]
I think signal might never be on fdroid see : https://fdroid.eutopia.cz/
