### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by rugk** [droidbreak/droidbreak.github.io#45]
Come on, you need HTTPS! Especially for sites which are about privacy/security...

It's just a few clicks away: https://letsencrypt.org/

**Comment by repat** [comment]
HTTPS is enabled via cloudflare. GitHub Pages does not support letsencrypt.

**Comment by rugk** [comment]
Hmmm okay, at least something. But there is no redirect from the HTTP version: http://droid-break.info/

And the links in your repo description and so only use the HTTP link.
