### ISSUE TITLE
Firefox F-Droid link is broken

### ISSUE THREAD

**Issue by gkaklas** [droidbreak/droidbreak.github.io#60]
Firefox isn't on F-Droid anymore, so the link to the F-Droid page returns a 404. I guess the alternatives are:
* Fennec, in which proprietary binaries have been removed
* Firefox Klar (Focus)
* FFUpdater, which helps the user download firefox directly from Mozilla (I think)

I think Fennec is the closest to upstream and seems to have more frequent updates, but still, it isn't Firefox, so a new entry would have to be created?

**Comment by dimqua** [comment]
IMO, Firefox shouldn't be recommended.
