### ISSUE TITLE
drop Signal

### ISSUE THREAD

**Issue by ghost** [droidbreak/droidbreak.github.io#67]
Signal has a [HUGE list of privacy abuses](https://github.com/privacytoolsIO/privacytools.io/issues/779), forcing users into OWS's own exclusive walled-garden as well as:

* Google Playstore walled-garden
* Google's search filter bubble in aggregation with Playstore assets
* Amazon's filter bubble
* CloudFlare's walled-garden of privacy abuses
* CDMA+GSM systems of surveillance (and consequential forced-feeding of privacy abusers AT&T, Verizon, Sprint, and T-mobile in the US)

I suggest Jami as an alternative.

**Comment by pahakalle** [comment]
Jami seems to use google firebase and also has a firebase tracker in the app https://reports.exodus-privacy.eu.org/en/reports/63024/ and there has been a lot of reports of messages being lost and bad audio/video quality (not sure if these are true anymore i have not used jami in a while)
