### ISSUE TITLE
Update your website to fix broken links or take it down.

### ISSUE THREAD

**Issue by ghost** [droidbreak/droidbreak.github.io#68]
The Firefox and Icecat F-Droid links are both 404, and the Lightning browser F-Droid link leads to a general apps overview page instead of the page for Lightning browser itself.  Some (many I'm sure) of the Play store links are dead too.  Some of the apps such as orWall haven't been updated in over half a decade now.

I do appreciate the list and the work you've done.  I have used it many times in the past to send to people to try to get them to move to better alternatives.  However if it's not going to be updated it should be taken down.  The main Prism Break site pretty much does what this does now anyway.  You could even redirect to that if you wanted.

**Comment by repat** [comment]
Yea, it could be updated, maybe you could write a pull request? :) I didn't really have time to maintain this much but any contributions are welcome.

I don't think it should be taken down

**Comment by ghost** [comment]
I am also quite busy, and it's also not my site.

Thanks anyway.
